insert into Owners(name, address, phone) values ('Jose', 'C/Benavente 2', '644476117');
insert into Owners(name, address, phone) values ('Ana', 'C/Benavente 3', '644476118');
insert into Owners(name, address, phone) values ('Luis', 'C/Benavente 4', '644476119');
insert into Owners(name, address, phone) values ('Maria', 'C/Benavente 5', '644476120');
insert into Owners(name, address, phone) values ('Pedro', 'C/Benavente 6', '644476121');
insert into Owners(name, address, phone) values ('Laura', 'C/Benavente 7', '644476122');
insert into Owners(name, address, phone) values ('Javier', 'C/Benavente 8', '644476123');
insert into Owners(name, address, phone) values ('Sara', 'C/Benavente 9', '644476124');

insert into Pets(name, birth_date, species, weight, chipped, picture_url, owner_id) values ('Pipo', '2024-01-01', 'BIRD', '0.01', false, 'bird.png', 1);
insert into Pets(name, birth_date, species, weight, chipped, picture_url, owner_id) values ('Lola', '2024-01-02', 'BIRD', '0.02', false, 'bird.png', 2);
insert into Pets(name, birth_date, species, weight, chipped, picture_url, owner_id) values ('Rocco', '2024-01-03', 'DOG', '0.03', false, 'dog.png', 3);
insert into Pets(name, birth_date, species, weight, chipped, picture_url) values ('Luna', '2024-01-04', 'DOG', '0.04', false, 'dog.png');
insert into Pets(name, birth_date, species, weight, chipped, picture_url) values ('Mimi', '2024-01-05', 'CAT', '0.05', false, 'cat.png');
insert into Pets(name, birth_date, species, weight, chipped, picture_url) values ('Nina', '2024-01-06', 'CAT', '0.06', false, 'cat.png');
insert into Pets(name, birth_date, species, weight, chipped, picture_url) values ('Toby', '2024-01-07', 'DOG', '0.07', false, 'dog.png');
insert into Pets(name, birth_date, species, weight, chipped, picture_url) values ('Milo', '2024-01-08', 'DOG', '0.08', false, 'dog.png');
insert into Pets(name, birth_date, species, weight, chipped, picture_url) values ('Coco', '2024-01-09', 'CAT', '0.09', false, 'cat.png');
insert into Pets(name, birth_date, species, weight, chipped, picture_url, owner_id) values ('Leo', '2024-01-10', 'CAT', '0.10', false, 'cat.png', 3);
insert into Pets(name, birth_date, species, weight, chipped, picture_url, owner_id) values ('Bella', '2024-01-11', 'DOG', '0.11', false, 'dog.png', 4);
insert into Pets(name, birth_date, species, weight, chipped, picture_url, owner_id) values ('Max', '2024-01-12', 'DOG', '0.12', false, 'dog.png', 5);
insert into Pets(name, birth_date, species, weight, chipped, picture_url, owner_id) values ('Charlie', '2024-01-13', 'CAT', '0.13', false, 'cat.png', 6);
insert into Pets(name, birth_date, species, weight, chipped, picture_url, owner_id) values ('Lucy', '2024-01-14', 'CAT', '0.14', false, 'cat.png', 7);
insert into Pets(name, birth_date, species, weight, chipped, picture_url) values ('Rocky', '2024-01-15', 'DOG', '0.15', false, 'dog.png');
insert into Pets(name, birth_date, species, weight, chipped, picture_url) values ('Daisy', '2024-01-16', 'DOG', '0.16', false, 'dog.png');
insert into Pets(name, birth_date, species, weight, chipped, picture_url, owner_id) values ('Chester', '2024-01-17', 'CAT', '0.17', false, 'cat.png', 3);
insert into Pets(name, birth_date, species, weight, chipped, picture_url, owner_id) values ('Sophie', '2024-01-18', 'CAT', '0.18', false, 'cat.png', 4);
insert into Pets(name, birth_date, species, weight, chipped, picture_url) values ('Buddy', '2024-01-19', 'DOG', '0.19', false, 'dog.png');
insert into Pets(name, birth_date, species, weight, chipped, picture_url) values ('Sadie', '2024-01-20', 'DOG', '0.20', false, 'dog.png');
insert into Pets(name, birth_date, species, weight, chipped, picture_url, owner_id) values ('Oliver', '2024-01-21', 'CAT', '0.21', false, 'cat.png', 7);
insert into Pets(name, birth_date, species, weight, chipped, picture_url, owner_id) values ('Maggie', '2024-01-22', 'CAT', '0.22', false, 'cat.png', 1);
insert into Pets(name, birth_date, species, weight, chipped, picture_url, owner_id) values ('Bailey', '2024-01-23', 'DOG', '0.23', false, 'dog.png', 2);
insert into Pets(name, birth_date, species, weight, chipped, picture_url, owner_id) values ('Zoe', '2024-01-24', 'DOG', '0.24', false, 'dog.png', 3);
insert into Pets(name, birth_date, species, weight, chipped, picture_url, owner_id) values ('Tucker', '2024-01-25', 'CAT', '0.25', false, 'cat.png', 4);
insert into Pets(name, birth_date, species, weight, chipped, picture_url, owner_id) values ('Chloe', '2024-01-26', 'CAT', '0.26', false, 'cat.png', 5);